---
- name: Ensure access on all servers
  wait_for:
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    port: 22
    state: started
- name: Load all facts
  setup:
    gather_subset:
      - 'all'
