- name: HP ILO Rest 
  yum_repository:
    name: HP-ILO-Rest
    description: HP ILO Rest Command Utility
    baseurl: https://downloads.linux.hpe.com/SDR/repo/ilorest/rhel/dist_ver/arch/project_ver
    file: HP-ILORest
    enabled: 1
    gpgcheck: 0
